# Generated by Django 5.1.2 on 2025-05-08 07:01

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ] 