# Generated by Django 5.1.2 on 2025-05-08 07:02

from django.db import migrations

def seed_llm_models(apps, schema_editor):
    LLMModel = apps.get_model("app", "LLMModel")
    
    # Initial models data
    models_data = [
        {
            'code': 'llama3.2:1b',
            'name': 'Llama 3.2 1B',
            'description': (
                'Llama 3.2 1B is a compact general purpose language model optimized for efficiency. '
                'It offers good performance for its size, making it suitable for a wide range of applications. '
                'This model provides a balance between speed and capability for daily tasks.'
            ),
        'logo': 'https://pbs.twimg.com/profile_images/16470ge89927269101570/pAVjQBOf_400x400.jpg',
        },
        {
            'code': 'qwen3:1.7b',
            'name': 'Qwen 3.1.7B',
            'description': (
                'Qwen 3 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models. '
                'The flagship model, Qwen3-235B-A22B, achieves competitive results in benchmark evaluations of coding, math, general capabilities, etc., when compared to '
                'other top-tier models such as DeepSeek-R1, o1, o3-mini, Grok-3, and Gemini-2.5-Pro. Additionally, the small MoE model offers excellent performance '
                'for efficient deployment.'
            ),
            'logo': 'https://avatars.githubusercontent.com/u/141221163?s=200&v=4',
        },
        {
            'code': 'hermes3:3b',
            'name': 'Hermes 3.3B',
            'description': (
                'Hermes 3 is a generalist language model with many improvements over Hermes 2, including advanced agentic capabilities, much better roleplaying, '
                'reasoning, multi-turn conversation, long context coherence, and improvements across the board. '
                'The ethos of the Hermes series of models is focused on aligning LLMs to the user, with powerful steering capabilities and control given to the end user.'
            ),
            'logo': 'https://cdn-uploads.huggingface.co/production/uploads/6317aade83d8d2fd903192d9/bMcZ3sNNQK8SRZpHXBmwM.jpeg',
        },
    ]
    
    for model_data in models_data:
        LLMModel.objects.update_or_create(
            code=model_data['code'],
            defaults={
                'name': model_data['name'],
                'description': model_data['description'],
                'logo': model_data['logo'],
            }
        )

def reverse_seed(apps, schema_editor):
    LLMModel = apps.get_model("app", "LLMModel")
    LLMModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vector'),
    ]

    operations = [
        migrations.RunPython(seed_llm_models, reverse_seed),
    ] 