# Generated by Django 5.1.2 on 2025-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_llm_models',
            field=models.CharField(choices=[('llama3.2:1b', 'Llama 3.2 1B'), ('deepseek-r1:1.5b', 'DeepSeek R1 1.5B')], default='llama3.2:1b', max_length=50),
        ),
    ]
