# Generated by Django 5.1.2 on 2025-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seed_llm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blurhash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
