# Generated by Django 5.1.2 on 2025-04-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_favorite_llm_models'),
    ]

    operations = [
    ]