# Generated by Django 5.1.2 on 2025-05-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_document_blurhash_document_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding process'),
        ),
    ]
