# Generated by Django 5.1.2 on 2025-04-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_convert_favorite_models'),
        ('app', '0005_modify_favorite_llm_models'),
    ]

    operations = [
    ]
