# Generated by Django 5.1.2 on 2025-05-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_is_onboarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
