# Generated by Django 5.1.2 on 2025-04-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250420_0607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
