# Generated by Django 5.1.2 on 2025-04-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_llm_models',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_llm_models',
            field=models.ManyToManyField(blank=True, help_text='Which LLMs this user has favorited', related_name='favored_by', to='app.llmmodel'),
        ),
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.document')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['changed_at'], name='app_documen_changed_a05fe9_idx')],
            },
        ),
    ]