# Generated by Django 5.1.2 on 2025-04-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_seed_llm_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatushistory',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
