# Generated by Django 5.1.2 on 2025-04-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_documentstatushistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
